### ISSUE TITLE
🐛 Bug:  Custom Icon Badges Not Displaying in GitHub README

### ISSUE THREAD

**Issue by walifile** [DenverCoder1/custom-icon-badges#1018]
### Description

I have noticed that the custom icon badges provided by Demolab for my GitHub README are currently not being displayed. It appears that the icons are not loading, and I suspect that this may be due to an issue with Demolab's website or service.

### Steps to reproduce

I have checked my README file, and the code for including the Demolab icons appears to be correct.

Please investigate and resolve this issue as soon as possible to ensure that the custom icon badges provided by Demolab are displayed correctly in my GitHub README. Thank you.

**Comment by igorskyflyer** [comment]
Just to extend the issue's information, a `HTTP 502` (Bad gateway) error is served when trying to load the custom badges through this service.

<br>
<br>

Also, navigating to the site's root the following is printed:

>
> An error occurred in the application and your page could not be served. If you are the application owner, [check your logs for details](https://devcenter.heroku.com/articles/logging#view-logs).
>

Feel free to ask me anything if you have further questions about my observations. Hope this will get fixed soon, thanks! 🙏🏼

**Comment by MarioQuirosLuna** [comment]
The custom icon badges already displayed

**Comment by DenverCoder1** [comment]
I did a rollback to the October 30 build on Heroku.

Currently working to figure out which dependency update caused it to crash and revert the relevant changes

**Comment by walifile** [comment]
The custom icon badges are now displaying correctly in the README. The issue has been resolved. Closing this now. Thanks!
