### ISSUE TITLE
❓ Question: Distribution of generated SVGs

### ISSUE THREAD

**Issue by igorskyflyer** [DenverCoder1/custom-icon-badges#1023]
### Description

Hello, I've been using your service for quite some time and it worked great until yesterday - which made me wonder - is self-hosting the only way to ensure ~100% of uptime?  
Or are we allowed to download the generated SVGs and store them in a repository as static files and use them accordingly?

P.S. of course, this refers to static badges (not dynamically generated ones, e.g. commit count, issue count, etc.) and this project would be credited in the repository's README file.

Thanks. 🙏🏼

**Comment by DenverCoder1** [comment]
Feel free to use it however you like. If you want to host generated static files, that's fine, attribution is great, although not required. If you want to host the entire project yourself, that's fine as well as long as it retains the license.

**Comment by igorskyflyer** [comment]
Thanks for the prompt reply!

Indeed, no site/service has a 100% uptime, hence the tilde (~) symbol. 😉
For now, I think I'll host static SVGs that I need to be available 100% of time in the repository where they are used and continue using the service when needed = dynamic badges.

Thanks. 🙏🏼
