### ISSUE TITLE
Heroku Application Error

### ISSUE THREAD

**Issue by superatomic** [DenverCoder1/custom-icon-badges#414]
**Describe the bug**
The website https://custom-icon-badges.herokuapp.com/ is broken.

**To Reproduce**
1. Go to https://custom-icon-badges.herokuapp.com/
2. See "Application error"

**Expected behavior**
The site should be functional.

**Screenshots**
![Application error
An error occurred in the application and your page could not be served. If you are the application owner, [check your logs for details](https://devcenter.heroku.com/articles/logging#view-logs). You can do this from the Heroku CLI with the command
`heroku logs --tail`](https://user-images.githubusercontent.com/51250849/168963813-171b1f54-8581-46ab-81c3-fa4a938a036c.jpeg)

![Project homepage with broken badges](https://user-images.githubusercontent.com/51250849/168963807-e69418ad-6b49-4244-b59b-72ee38de6f54.jpeg)

**Comment by ThatOneCalculator** [comment]
It's still down... 😔
