### ISSUE TITLE
Badges stopped appearing

### ISSUE THREAD

**Issue by polar0** [DenverCoder1/custom-icon-badges#652]
Hi there.

All my badges stopped appearing last time I checked, which is today. I have no idea when it stopped working. Some can be registered with the same slug, some cannot (`slug already in use`).

Any idea why it's happening?

Here is how it appears:
<img width="615" alt="image" src="https://user-images.githubusercontent.com/99199454/203493114-a8004053-fa39-4b1a-ada2-6bb697e25f8a.png">

The ones correctly appearing are from the original https://shields.io/

The code didn't change, and used to work correctly. I.e:
`[alchemy]: https://custom-icon-badges.demolab.com/badge/Alchemy-2356D2?style=for-the-badge&logo=alchemy&logoColor=white`

Thanks!

**Comment by DenverCoder1** [comment]
Fixed by #653

(axios breaking things again)

**Comment by DenverCoder1** [comment]
I have replaced all uses of `axios` with `node-fetch` now, since I feel it is more likely to be stable and not unexpectedly release broken versions.

**Comment by polar0** [comment]
@DenverCoder1 Absolutely no need to apologize!

Thank you very much for the quick fix, and for that fantastic tool!
