### ISSUE TITLE
❓ Question: Can I re-upload a svg logo in https://custom-icon-badges.demolab.com/

### ISSUE THREAD

**Issue by Giresharu** [DenverCoder1/custom-icon-badges#858]
### Description

I upload a flawed svg logo named "openupm" to https://custom-icon-badges.demolab.com/ and submit it.
I forgot to combine the outline of path when I was making svg, it will make the logoColor weird. 
Could you delete it? I'll upload the correct version.

Sorry for my carelessness!

**Comment by DenverCoder1** [comment]
openupm is now available again

Let me know if there's anything else I can with

**Comment by Giresharu** [comment]
> openupm is now available again
> 
> Let me know if there's anything else I can with

Thanks for your work!
