### ISSUE TITLE
🐛 Bug: custom badge stopped appearing

### ISSUE THREAD

**Issue by shikharish** [DenverCoder1/custom-icon-badges#969]
### Description

My custom badge stopped working. I don't know exactly when but I noticed it today. The original ones(from [shields.io](shields.io)) are showing properly.
The badge is showing but the icon is missing.
![image](https://github.com/DenverCoder1/custom-icon-badges/assets/139053348/5030ac70-a31b-4ad9-9053-75b5dacd37ee)
Earlier it was like:
![image](https://github.com/DenverCoder1/custom-icon-badges/assets/139053348/d238b647-77e2-4668-9d6d-36f6249e31eb)

### Steps to reproduce

Here's the code:
`[wiki-shield]: https://custom-icon-badges.demolab.com/badge/metakgp_wiki-grey?logo=metakgp_logo&logoColor=white&style=for-the-badge`

**Comment by DenverCoder1** [comment]
Thanks for reporting the issue!

It seems it is an issue that came up when feather icons were introduced and the logoColor code was refactored.

Note: **logoColor is only for SVG icons and is not supported for PNG images such as this one**

I will try to fix the issue for compatibility, but for now you can (and should) remove the logoColor parameter:

https://custom-icon-badges.demolab.com/badge/metakgp_wiki-grey?logo=metakgp_logo&style=for-the-badge

![](https://custom-icon-badges.demolab.com/badge/metakgp_wiki-grey?logo=metakgp_logo&style=for-the-badge)
