### ISSUE TITLE
Show loading animation when request is being submitted

### ISSUE THREAD

**Issue by DenverCoder1** [DenverCoder1/custom-icon-badges#99]
Submitting an icon can take a few seconds at times so, it would be useful to see confirmation that the request has gone through.

It is also useful since if the response is the same as the previous one, it is hard to tell that it has finished and updated the message.

**Comment by Armakuji** [comment]
I'm done. Check out this pull request  https://github.com/DenverCoder1/custom-icon-badges/pull/172 .
